format = """$all$fill$time$line_break$character"""

[fill]
symbol = " "

[character]
success_symbol = "[](bold fg:#a9b1d6)"
error_symbol = "[](bold fg:#f7768e)"

[username]
format = "[$user]($style)   "
style_user = "bold dimmed fg:#7aa2f7"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)   in "
ssh_only = false
style = "bold fg:#449dab"

[git_branch]
style = "bold fg:#A3BE8C"

[git_status]
disabled = true

[directory]
style = "bold fg:#7da6ff"

[cmd_duration]
style = "fg:#ff9e64"

[python]
format = 'via [${symbol}${pyenv_prefix}(${version})]($style) [(\($virtualenv\))](bold yellow)'
style = "bold blue"
symbol = " "

[lua]
symbol = "󰢱 "

[golang]
symbol = " "

[c]
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]
symbol = " "

[rust]
symbol = "󱘗 "

[cmake]
symbol = " "
style="green"

[time]
disabled = false
style = "fg:#ad8ee6"
format = '[ $time]($style) '
time_format = '%R'
