[character]
success_symbol = "[](bold white)"
error_symbol = "[](bold red)"

[username]
format = "[$user]($style)   "
style_user = "bold dimmed green"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)   in "
ssh_only = false
style = "bold green"

[python]
format = 'via [${symbol}${pyenv_prefix}(${version})]($style) [(\($virtualenv\))](bold yellow)'
style = "bold blue"
symbol = " "

[lua]
symbol = "󰢱 "

[golang]
symbol = " "

[c]
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]
symbol = " "

[rust]
symbol = "󱘗 "

[cmake]
symbol = " "
style="green"
