require("plugins.setups.colorscheme")
require("plugins.setups.lualine")
require("plugins.setups.telescope")
require("plugins.setups.treesitter")
require("plugins.setups.lsp-config")
require("plugins.setups.gitsigns")
require("plugins.setups.cmp")
